# Generated by Django 4.0.4 on 2022-04-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto_curso',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
